Distribuição Binomial
```{r}
# Se jogar uma moeda 5 vezes, qual a probabilidade de dar cara 3 vezes?
# x = eventos, p = probabilidades, size = eventos
dbinom(x = 3, size = 5, prob = 0.5)
```
Se eu passar 4 sinais de quatro tempos cada, qual a probabilidade de eu pegar 0,1,2,3 e 4 sinais verdes?
```{r}
# q = teste de espaço amostral,  size = tamanho da amostra, prob = probabilidade (1 / 4)

pbinom(q = 1, size = 4, prob = 0.25)
```
Se fizer uma prova de um concurso com 12 questões, se chutar todas qual a prob de acertar 7? Com 4 alternativas por questão
```{r}
# x = probabilidade a ser encontrada, size = tamanho da amostra, prob = probabilidade (1 / 4)
dbinom(x = 7, size = 12, prob = 0.25)
```
Se eu passar 4 sinais de quatro tempos cada, qual a probabilidade de eu pegar 3 ou mais sinais verdes?
```{r}
# q = teste de espaço amostral, size = tamanho da amostra, prob = probabilidade (1 / 4), lower.tail = F calcula a probabilidade do tipo MAIOR QUE
pbinom(q = 2, size = 4, prob = 0.25, lower.tail = F)
dbinom(x = 3, size = 4, prob = 0.25) + dbinom(x = 4, size = 4, prob = 0.25)
1 - pbinom(q = 2, size = 4, prob = 0.25)
```

 